### PR TITLE
QT5.12 and c++11 support

### LINKED ISSUE #101: QT5.11 / C++11 changes
#92 upgraded to QT 5.9, in Ubuntu 18.04.

QT5.11 in Debian 10 requires c++11, this should be changed in the waffile

When upgrading to C++11, `gvarlengtharray.h` fails to compile because of the use of memcpy.
I see that this file appears to be an almost direct copy of [qvarlengtharray](https://doc.qt.io/qt-5/qvarlengtharray.html) from QT, and then renamed q->g. I'm not sure why it's been copied into the gaia code and renamed. @dbogdanov do you have any idea about this? It seems like we could just directly use qvarlengtharray here

We should also check on the latest QT, 5.14.

### LINKED ISSUE #105: warnings
```
../src/descriptortree.cpp:664:14: warning: ‘QDataStream& gaia2::operator<<(QDataStream&, const gaia2::DescriptorTree&)’ has not been declared within gaia2
 QDataStream& gaia2::operator<<(QDataStream& out, const DescriptorTree& tree) {
              ^~~~~
In file included from ../src/descriptortree.cpp:21:0:
../src/descriptortree.h:312:23: note: only here as a friend
   friend QDataStream& operator<<(QDataStream& out, const DescriptorTree& tree);
                       ^~~~~~~~
../src/descriptortree.cpp:673:14: warning: ‘QDataStream& gaia2::operator>>(QDataStream&, gaia2::DescriptorTree&)’ has not been declared within gaia2
 QDataStream& gaia2::operator>>(QDataStream& in, DescriptorTree& tree) {
              ^~~~~
In file included from ../src/descriptortree.cpp:21:0:
../src/descriptortree.h:313:23: note: only here as a friend
   friend QDataStream& operator>>(QDataStream& in, DescriptorTree& tree);
```

```
../src/dataset.cpp:956:14: warning: ‘QDataStream& gaia2::operator<<(QDataStream&, const gaia2::DataSet&)’ has not been declared within gaia2
 QDataStream& gaia2::operator<<(QDataStream& out, const DataSet& dataset) {
              ^~~~~
In file included from ../src/dataset.cpp:25:0:
../src/dataset.h:486:23: note: only here as a friend
   friend QDataStream& operator<<(QDataStream& out, const DataSet& dataset);
                       ^~~~~~~~
../src/dataset.cpp:983:14: warning: ‘QDataStream& gaia2::operator>>(QDataStream&, gaia2::DataSet&)’ has not been declared within gaia2
 QDataStream& gaia2::operator>>(QDataStream& in, DataSet& dataset) {
              ^~~~~
In file included from ../src/dataset.cpp:25:0:
../src/dataset.h:487:23: note: only here as a friend
   friend QDataStream& operator>>(QDataStream& in, DataSet& dataset);
                       ^~~~~~~~
```

```
../src/region.cpp:42:14: warning: ‘QDataStream& gaia2::operator<<(QDataStream&, const gaia2::Segment&)’ has not been declared within gaia2
 QDataStream& gaia2::operator<<(QDataStream& out, const Segment& segment) {
              ^~~~~
In file included from ../src/region.cpp:20:0:
../src/region.h:116:23: note: only here as a friend
   friend QDataStream& operator<<(QDataStream& out, const Segment& segment);
                       ^~~~~~~~
../src/region.cpp:49:14: warning: ‘QDataStream& gaia2::operator>>(QDataStream&, gaia2::Segment&)’ has not been declared within gaia2
 QDataStream& gaia2::operator>>(QDataStream& in, Segment& segment) {
              ^~~~~
In file included from ../src/region.cpp:20:0:
../src/region.h:117:23: note: only here as a friend
   friend QDataStream& operator>>(QDataStream& in, Segment& segment);
                       ^~~~~~~~
```

```
../src/point.cpp:30:14: warning: ‘QDataStream& gaia2::operator<<(QDataStream&, const gaia2::Scope&)’ has not been declared within gaia2
 QDataStream& gaia2::operator<<(QDataStream& out, const Scope& scope) {
              ^~~~~
In file included from ../src/point.cpp:25:0:
../src/point.h:68:23: note: only here as a friend
   friend QDataStream& operator<<(QDataStream& out, const Scope& scope);
                       ^~~~~~~~
../src/point.cpp:34:14: warning: ‘QDataStream& gaia2::operator>>(QDataStream&, gaia2::Scope&)’ has not been declared within gaia2
 QDataStream& gaia2::operator>>(QDataStream& in, Scope& scope) {
              ^~~~~
In file included from ../src/point.cpp:25:0:
../src/point.h:69:23: note: only here as a friend
   friend QDataStream& operator>>(QDataStream& in, Scope& scope);
                       ^~~~~~~~
../src/point.cpp:702:14: warning: ‘QDataStream& gaia2::operator<<(QDataStream&, const gaia2::Point&)’ has not been declared within gaia2
 QDataStream& gaia2::operator<<(QDataStream& out, const Point& point) {
              ^~~~~
In file included from ../src/point.cpp:25:0:
../src/point.h:308:23: note: only here as a friend
   friend QDataStream& operator<<(QDataStream& out, const Point& point);
                       ^~~~~~~~
../src/point.cpp:707:14: warning: ‘QDataStream& gaia2::operator>>(QDataStream&, gaia2::Point&)’ has not been declared within gaia2
 QDataStream& gaia2::operator>>(QDataStream& in, Point& point) {
              ^~~~~
In file included from ../src/point.cpp:25:0:
../src/point.h:309:23: note: only here as a friend
   friend QDataStream& operator>>(QDataStream& in, Point& point);
                       ^~~~~~~~
```

```
../src/pointlayout.cpp:533:14: warning: ‘QDataStream& gaia2::operator<<(QDataStream&, const gaia2::PointLayout&)’ has not been declared within gaia2
 QDataStream& gaia2::operator<<(QDataStream& out, const PointLayout& layout) {
              ^~~~~
In file included from ../src/pointlayout.cpp:21:0:
../src/pointlayout.h:303:23: note: only here as a friend
   friend QDataStream& operator<<(QDataStream& out, const PointLayout& layout);
                       ^~~~~~~~
../src/pointlayout.cpp:537:14: warning: ‘QDataStream& gaia2::operator>>(QDataStream&, gaia2::PointLayout&)’ has not been declared within gaia2
 QDataStream& gaia2::operator>>(QDataStream& in, PointLayout& layout) {
              ^~~~~
In file included from ../src/pointlayout.cpp:21:0:
../src/pointlayout.h:304:23: note: only here as a friend
   friend QDataStream& operator>>(QDataStream& in, PointLayout& layout);
                       ^~~~~~~~
```

### PR DESCRIPTION
**Pull request by alastair**
Fixes #105 
Fixes #101

An extension on the work that was done for qt5. When approved we can merge this into the qt5 branch and rebase it against master so that we can run comparative tests against qt4

### CODE REVIEW

File: src/dataset.h [hunk 1]
```diff
@@ -488,6 +488,8 @@ class DataSet : public PointArray, public QObject {
 
 };
 
+QDataStream& operator<<(QDataStream& out, const DataSet& dataset);
+QDataStream& operator>>(QDataStream& in, DataSet& dataset);
```
Comment (alastair) [inline src/dataset.h]: My understanding of this warning (#105) is that we define this function as a friend for the class, but we don't actually provide a forward declaration of the function. With recent g++'s, you need to do both. You can't implicitly forward-declare the function by adding it as a friend function to a class.

File: src/searchspacepool_impl.h [hunk 2]
```diff
@@ -121,8 +121,18 @@ BaseSearchSpace<SearchPointType, DataSetType>* BaseSearchSpacePool<SearchPointTy
...
+            break;
+        }
+        is = qMax(is, 0);
+    }
+    for (ie=0; ie<steps.size(); ie++) {
+        if (steps[ie] >= end) {
+            break;
+        }
+        ie = qMin(ie, steps.size()-1);
+    }
```
Comment (alastair) [inline src/searchspacepool_impl.h]: I think this is wrong - the braces around `for` should only be around the if/break. The qMax/qMin should be outside the for loop. Can someone confirm this?

Comment (alastair) [reply src/searchspacepool_impl.h]: fixed
